// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS4pmWibuu2Fbi-yKDAekJm7VGwRa1I8I',
    appId: '1:940057841077:web:3f215aa97cc7b17ad89dfc',
    messagingSenderId: '940057841077',
    projectId: 'chat-flutter-2d488',
    authDomain: 'chat-flutter-2d488.firebaseapp.com',
    storageBucket: 'chat-flutter-2d488.appspot.com',
    measurementId: 'G-FPL92H8SF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsrf15eBgP7cKApKBMLP1d7YNYKOy9Tio',
    appId: '1:940057841077:android:06a5a04b7f132c2cd89dfc',
    messagingSenderId: '940057841077',
    projectId: 'chat-flutter-2d488',
    storageBucket: 'chat-flutter-2d488.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdmTmGitEZ43i_0GF9zMNoLm5DzW-TayU',
    appId: '1:940057841077:ios:41840b5fa33be092d89dfc',
    messagingSenderId: '940057841077',
    projectId: 'chat-flutter-2d488',
    storageBucket: 'chat-flutter-2d488.appspot.com',
    iosClientId: '940057841077-6uei0q96p5rusagj87a4rmrhuo5cksn5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstFlutter',
  );
}
